inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "db/**/*"
    - "lib/tasks/**/*"

  TargetRubyVersion: 2.5


Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true
